name: product_hunt
description: "A new Flutter project."


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"







dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.5
  http: ^1.2.2
  image_picker: ^1.1.2
  mime: ^1.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter




flutter:
  
  
  
  uses-material-design: true
  assets:
    - .env